name: CI/CD for NestJS with Docker and Nginx

on:
  push:
    branches:
      - main # Thay bằng branch bạn muốn triển khai (ví dụ: `main`)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Bước 2: Set up Node.js (để kiểm tra mã nguồn)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Bước 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Bước 4: Run tests (nếu bạn có test)
      - name: Run tests
        run: npm test

      # Bước 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Bước 6: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t your-dockerhub-username/nestjs-app:latest .
          docker push your-dockerhub-username/nestjs-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Bước 7: Deploy to server via SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull your-dockerhub-username/nestjs-app:latest
            docker-compose down
            docker-compose up -d
